name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up sidewinder
        shell: bash
        run: |
          git clone --depth 1 --branch v0.1.7 https://github.com/Pinjontall94/sidewinder.git
          cp -r content static template.html -t sidewinder/
          cd sidewinder && python3 -m venv venv
          venv/bin/pip3 install -r requirements.txt

      - name: Build site
        shell: bash
        run: venv/bin/python3 src/main.py
          
